#!/usr/bin/env python3

from dbus import SessionBus, Interface
from dbus.exceptions import DBusException

from sys import exit

if __name__ == "__main__":
    bus = SessionBus()

    try: 
        lock_forwarder = Interface(bus.get_object("org.lockforward", "/"),
                dbus_interface="org.lockforward")
    except DBusException:
        print("No lock-forward is available for this session")
        exit(1)

    lock_forwarder.lock_now()
